version: '3.3'
services:
  web:
      build:
          context: ./
          dockerfile: web.docker
      volumes:
        - ./:/var/www/html/newtransflow
      ports:
        - "8090:80"
      links:
        - app
  app:
      build:
        context: ./
        dockerfile: app.docker
      volumes:
        - ./:/var/www/html/newtransflow
